FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
RUN addgroup -S spring && adduser -S spring -G spring
USER spring
COPY target/*.jar app.jar
EXPOSE 8081 
ENTRYPOINT ["java","-Xms64m","-Xmx256m","-Dspring.profiles.active=docker","-jar","app.jar"]