server:
  port: 8761

spring:
  application:
    name: eureka-server
  security:
    user:
      name: admin
      password: medibook123

eureka:
  instance:
    hostname: eureka-server          # ← CHANGE from localhost to eureka-server
    prefer-ip-address: false
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://admin:medibook123@eureka-server:8761/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false

management:
  endpoints:
    web:
      exposure:
        include: health,info